notifications:
  on_success: never
  on_failure: never

language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    env:
      - PY_VERSION='3.4'
      - COMPLETE=false
      - BIN=true
      - SRC=false
  - os: linux
    dist: trusty
    sudo: false
    env:
      - PY_VERSION='3.5'
      - COMPLETE=false
      - BIN=true
      - SRC=false
  - os: linux
    dist: trusty
    sudo: false
    env:
      - PY_VERSION='3.6'
      - COMPLETE=true
      - BIN=true
      - SRC=true
  - os: osx
    env:
      - PY_VERSION='3.4'
      - COMPLETE=false
      - BIN=true
      - SRC=false
  - os: osx
    env:
      - PY_VERSION='3.5'
      - COMPLETE=false
      - BIN=true
      - SRC=false
  - os: osx
    env:
      - PY_VERSION='3.6'
      - COMPLETE=false
      - BIN=true
      - SRC=false

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then MINICONDA=Miniconda3-latest-Linux-x86_64.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh; fi
  - wget https://repo.continuum.io/miniconda/$MINICONDA
  
  - bash $MINICONDA -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n biotite-env python=$PY_VERSION
  - source activate biotite-env
  
  - conda install -n biotite-env -c anaconda cython
  - conda install -n biotite-env -c anaconda pytest
  - conda install -n biotite-env -c anaconda numpy
  - conda install -n biotite-env -c conda-forge matplotlib
  - if [ $COMPLETE == true ]; then conda install -n biotite-env -c anaconda pandas; fi
  - if [ $COMPLETE == true ]; then conda install -n biotite-env -c anaconda scipy; fi
  - if [ $COMPLETE == true ]; then conda install -n biotite-env -c conda-forge mdtraj; fi
  - if [ $COMPLETE == true ]; then conda install -n biotite-env -c conda-forge sphinx; fi
  - if [ $COMPLETE == true ]; then conda install -n biotite-env -c anaconda numpydoc; fi

script:
  - python setup.py test --pytest-args="--ignore=tests/application/"

before_deploy:
  - if [ $SRC == true ]; then python setup.py sdist; fi
  - if [ $BIN == true ]; then python setup.py bdist_wheel; fi
  - if [ $BIN == true ]; then rename 's/linux/manylinux1/g' dist/*.whl; fi
  - if [ $COMPLETE == true ]; then python setup.py build_sphinx; fi
  - if [ $COMPLETE == true ]; then tar -cf doc/_build/doc.tar doc/_build/html/; fi

deploy:
  provider: releases
  api-key:
    secure: ncH32tO1V1vJMgpHY/JJ+TDpFkj0uFzNVeD2tBFq+uCDSRzQo8hiC+kFveciQNr9UuKFyqBySFpjP+g93f9xWcjruzTbT42vhoM6YzddMcQI/yiINWoco1Lk8RZpv6HsWeLXPFzP6BWWwBH+1rF09AXX4hk5nHGOlawM+f1nwCoqZrvPc5mhfN/JytRgUjjVZ1yI9VL77wMakGYsuuBpgjpk1AC5bG2X0aCYSRub7kAl3CYPvrknx38pbtL8d9mMyFwLe1UVxuyhY5PZ1hzk+6Dkjwx0mWQ95TCoTOwPU2ECF81gORVd/HZeQ/xRPYb8mlufy+v7pjUgMRQVMwjRR+e3JYHxoAjbN41WUYZohyIeVGnQ9hlaa59EHoDyGL6hJFqJ2o7E5DoKCGE+ssQ/pAmczPMCf3lG4nhgA80WXo9fcchMqPqB1uX43gv+qWvLy3N8V+pzK9nQpUsjKXKROp5fABIaz56APUaq1UrzaAvPHUlNiixjWd7FCU9nDGig8vGSfGNumBUFOQHnS12eQ0ICzTK7z9SuigkEAkB236AiopD5d0fZyyz9hWvWua22wqBD4kwtIQczFos5JHibv1taWdtnxs+/XAJpcV6EWYdTpNEItejRjtPRv20Ddx+G3176aYKbXWrANk/F4sp/HgGaLR7xUiH1wabd6QS5OUE=
  file:
    - dist/*
    - doc/_build/doc.tar
  file_glob: true
  on:
    repo: biotite-dev/biotite
    tags: true
  skip_cleanup: true
