language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
    env:
    - COMPLETE=true
    - BIN=true
    - SRC=true
install:
- pip install cython
- pip install pytest
- pip install numpy --only-binary=numpy
- pip install matplotlib --only-binary=matplotlib
- if [ $COMPLETE == true ]; then pip install pandas --only-binary=pandas; fi
- if [ $COMPLETE == true ]; then pip install scipy --only-binary=scipy; fi
- if [ $COMPLETE == true ]; then pip install mdtraj; fi
- if [ $COMPLETE == true ]; then pip install sphinx; fi
- if [ $COMPLETE == true ]; then pip install numpydoc; fi
script:
- python setup.py test --pytest-args="--ignore=tests/application/"
before_deploy:
- if [ $SRC == true ]; then python setup.py sdist; fi
- if [ $BIN == true ]; then python setup.py bdist_wheel; fi
- if [ $BIN == true ]; then rename 's/linux/manylinux1/g' dist/*.whl; fi
- if [ $COMPLETE == true ]; then python setup.py build_sphinx; fi
- if [ $COMPLETE == true ]; then tar -cf doc.tar doc/_build/html/; fi
deploy:
  provider: releases
  file:
  - dist/*
  - doc/_build/doc.tar
  file_glob: true
  on:
    repo: biotite-dev/biotite
    tags: true