environment:
  matrix:
    - PYTHON: "C:\\Miniconda36"
      PY_VERSION: "3.7"
      NUMPY_VERSION: "1.15"
    - PYTHON: "C:\\Miniconda36-x64"
      PY_VERSION: "3.7"
      NUMPY_VERSION: "1.15"
    - PYTHON: "C:\\Miniconda36"
      PY_VERSION: "3.8"
      NUMPY_VERSION: "1.15"
    - PYTHON: "C:\\Miniconda36-x64"
      PY_VERSION: "3.8"
      NUMPY_VERSION: "1.15"
    - PYTHON: "C:\\Miniconda36"
      PY_VERSION: "3.9"
      NUMPY_VERSION: "1.19"
    - PYTHON: "C:\\Miniconda36-x64"
      PY_VERSION: "3.9"
      NUMPY_VERSION: "1.19"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n biotite-dev -c anaconda python=%PY_VERSION%
  - conda install -n biotite-dev -c anaconda -c conda-forge "cython>=0.29" numpy=%NUMPY_VERSION% "requests>=2.12" "msgpack-python>=0.5.6" "pytest>=3.2"
  - activate biotite-dev
  - python setup.py bdist_wheel
  - pip install --find-links=.\dist biotite

build: false

test_script:
  - pytest --ignore=tests//structure//test_trajectory.py --ignore=tests//application --ignore=tests//database

artifacts:
  - path: dist\*
