environment:
  matrix:
    - PYTHON: "C:\\Miniconda36"
      PY_VERSION="3.6"
    - PYTHON: "C:\\Miniconda36-x64"
      PY_VERSION="3.6"
    - PYTHON: "C:\\Miniconda36"
      PY_VERSION="3.7"
    - PYTHON: "C:\\Miniconda36-x64"
      PY_VERSION="3.7"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n biotite-env python=$PY_VERSION cython, pytest, numpy
  - activate biotite-env

build: false

test_script:
  - python setup.py test --pytest-args="--ignore=tests/structure/test_trajectory.py --ignore=tests/application/"

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*
