{% set version = "0.7.0" %}

package:
  name: biotite
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: "https://github.com/biotite-dev/biotite"
  folder: conda-dist

build:
  script: $PYTHON $RECIPE_DIR/setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.6
    - setuptools
    - wheel
    - cython >=0.28
    - numpy
  run:
    - python >=3.6
    - requests
    - numpy
    - msgpack-python

about:
  home: https://www.biotite-python.org/
  license: BSD 3-Clause
  license_file: LICENSE.rst
  summary: "A comprehensive framework for computational molecular biology"