name: Testing Biotite

on: [push, pull_request]

jobs:
  test-simple:
    name: Testing Biotite without database accesses and external applications runs
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: '3.7'
            numpy: '1.15'
          - os: ubuntu-latest
            python: '3.8'
            numpy: '1.16'
          - os: macos-latest
            python: '3.7'
            numpy: '1.15'
          - os: macos-latest
            python: '3.8'
            numpy: '1.16'
          - os: macos-latest
            python: '3.9'
            numpy: '1.19'

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: biotite-dev
          auto-update-conda: true
          python-version: ${{ matrix.python }}
      - run: conda install -c conda-forge "cython>=0.29" numpy=$NUMPY_VERSION "requests>=2.12" "msgpack-python>=0.5.6" "networkx>=2.0" "pytest>=3.2" 
        env:
          NUMPY_VERSION: ${{ matrix.numpy }}
      - run: python setup.py bdist_wheel
      - run: pip install ./dist/*.whl
      - run: pytest --ignore=tests/structure/test_trajectory.py --ignore=tests/application/ --ignore=tests/database/ --ignore=tests/test_doctest.py
  

  test-thorough:
    name: Testing Biotite thoroughly

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: biotite-dev
          environment-file: environment.yml
          auto-update-conda: true
          python-version: '3.9'
      - run: conda install numpy=1.19
      - run: python setup.py bdist_wheel
      - run: pip install ./dist/*.whl
      - run: pytest --ignore=tests/application/test_blast.py --ignore=tests/application/test_sra.py --ignore=tests/database/test_entrez.py